version: '3.4'

services:
  restapirepo:
    image: ${DOCKER_REGISTRY-}restapirepo
    build:
      context: .
      dockerfile: Rest Api Repo/Dockerfile
    env_file:
      - api.env
    networks:
      - my_network
    ports:
      - 5000:5000
    environment:
      ApiKey: ${ApiKey}
      CacheEnabled: ${CacheEnabled}
      CacheConnectionString: ${CacheConnectionString}
      ConnectionString: ${ConnectionString}
  sqldb:
    container_name: sqldb
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    networks:
      - my_network
    env_file:
      - ./db.env
    volumes:
      - .\data:/var/opt/mssql/data
  cache:
    container_name: cachedb
    image: redis:alpine
    networks:
      - my_network
    env_file:
      - cache.env
networks:
  my_network:
    driver: bridge
