version: '3.4'

services:
  restapirepo:
    image: ${DOCKER_REGISTRY-}restapirepoapi
    build:
      context: .
      dockerfile: src/RestApiRepo.API/Dockerfile
    env_file:
      - ./api.env
    networks:
      - my_network
    depends_on:
      - sqldb
      - cache
  apigateway:
    image: envoyproxy/envoy:v1.14.1
    ports:
      - "10000:10000"
    networks:
      - my_network
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./Envoy/https.crt:/etc/ssl/certs/https.crt
      - ./Envoy/key.pem:/etc/ssl/certs/key.pem
  sqldb:
    container_name: sqldb
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    networks:
      - my_network
    env_file:
      - ./db.env
    volumes:
      - .\data:/var/opt/mssql/data
  cache:
    container_name: cachedb
    image: redis:alpine
    networks:
      - my_network
    env_file:
      - cache.env
networks:
  my_network:
    driver: bridge
