version: "3.7"
services:
    db:
        container_name: db
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        ports:
        - "1433:1433"
        networks:
          - my_network
        env_file:
          - ./db.env
      
networks:
    my_network:
        driver: bridge